<a href="https://colab.research.google.com/github/yashkapur0403/23FE10CSE00593_Yash_Kapur_ML_Lab/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_selection import f_classif


In [111]:
df = pd.read_csv("/content/DATA (1).csv")
df.head()


STUDENT ID  1  2  3  4  5  6  7  8  9  ...  23  24  25  26  27  28  29  30  \
0   STUDENT1  2  2  3  3  1  2  2  1  1  ...   1   1   3   2   1   2   1   1   
1   STUDENT2  2  2  3  3  1  2  2  1  1  ...   1   1   3   2   3   2   2   3   
2   STUDENT3  2  2  2  3  2  2  2  2  4  ...   1   1   2   2   1   1   2   2   
3   STUDENT4  1  1  1  3  1  2  1  2  1  ...   1   2   3   2   2   1   3   2   
4   STUDENT5  2  2  1  3  2  2  1  3  1  ...   2   1   2   2   2   1   2   2   

   COURSE ID  GRADE  
0          1      1  
1          1      1  
2          1      1  
3          1      1  
4          1      1  

[5 rows x 33 columns]

In [112]:
df.info()
df.shape


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   STUDENT ID  145 non-null    object
 1   1           145 non-null    int64 
 2   2           145 non-null    int64 
 3   3           145 non-null    int64 
 4   4           145 non-null    int64 
 5   5           145 non-null    int64 
 6   6           145 non-null    int64 
 7   7           145 non-null    int64 
 8   8           145 non-null    int64 
 9   9           145 non-null    int64 
 10  10          145 non-null    int64 
 11  11          145 non-null    int64 
 12  12          145 non-null    int64 
 13  13          145 non-null    int64 
 14  14          145 non-null    int64 
 15  15          145 non-null    int64 
 16  16          145 non-null    int64 
 17  17          145 non-null    int64 
 18  18          145 non-null    int64 
 19  19          145 non-null    int64 
 20  20        

(145, 33)

In [113]:
df.describe()


1           2           3           4           5           6  \
count  145.000000  145.000000  145.000000  145.000000  145.000000  145.000000   
mean     1.620690    1.600000    1.944828    3.572414    1.662069    1.600000   
std      0.613154    0.491596    0.537216    0.805750    0.474644    0.491596   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      1.000000    1.000000    2.000000    3.000000    1.000000    1.000000   
50%      2.000000    2.000000    2.000000    3.000000    2.000000    2.000000   
75%      2.000000    2.000000    2.000000    4.000000    2.000000    2.000000   
max      3.000000    2.000000    3.000000    5.000000    2.000000    2.000000   

                7           8           9          10  ...          23  \
count  145.000000  145.000000  145.000000  145.000000  ...  145.000000   
mean     1.579310    1.627586    1.620690    1.731034  ...    1.337931   
std      0.495381    1.020245    1.061112    0.783999  ...    0.614870   
min      1.000000    1.000000    1.000000    1.000000  ...    1.000000   
25%      1.000000    1.000000    1.000000    1.000000  ...    1.000000   
50%      2.000000    1.000000    1.000000    2.000000  ...    1.000000   
75%      2.000000    2.000000    2.000000    2.000000  ...    2.000000   
max      2.000000    5.000000    4.000000    4.000000  ...    3.000000   

               24          25          26          27          28          29  \
count  145.000000  145.000000  145.000000  145.000000  145.000000  145.000000   
mean     1.165517    2.544828    2.055172    2.393103    1.806897    3.124138   
std      0.408483    0.564940    0.674736    0.604343    0.810492    1.301083   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      1.000000    2.000000    2.000000    2.000000    1.000000    2.000000   
50%      1.000000    3.000000    2.000000    2.000000    2.000000    3.000000   
75%      1.000000    3.000000    3.000000    3.000000    2.000000    4.000000   
max      3.000000    3.000000    3.000000    3.000000    3.000000    5.000000   

               30   COURSE ID       GRADE  
count  145.000000  145.000000  145.000000  
mean     2.724138    4.131034    3.227586  
std      0.916536    3.260145    2.197678  
min      1.000000    1.000000    0.000000  
25%      2.000000    1.000000    1.000000  
50%      3.000000    3.000000    3.000000  
75%      3.000000    7.000000    5.000000  
max      4.000000    9.000000    7.000000  

[8 rows x 32 columns]

In [114]:
df.isnull().sum()


STUDENT ID    0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            0
26            0
27            0
28            0
29            0
30            0
COURSE ID     0
GRADE         0
dtype: int64

In [115]:
# Convert multiclass grade to binary
df["GRADE"] = df["GRADE"].apply(lambda x: 1 if x >= 4 else 0)


In [116]:
df = df.drop(["STUDENT ID", "COURSE ID"], axis=1)


In [117]:
X = df.drop("GRADE", axis=1)

y = df["GRADE"]


In [118]:
df.columns


Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', 'GRADE'],
      dtype='object')

In [119]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [120]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [121]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train_scaled, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

In [122]:
y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.5517241379310345

Confusion Matrix:
 [[11  7]
 [ 6  5]]

Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.61      0.63        18
           1       0.42      0.45      0.43        11

    accuracy                           0.55        29
   macro avg       0.53      0.53      0.53        29
weighted avg       0.56      0.55      0.56        29



In [123]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.5517241379310345

Confusion Matrix:
 [[11  7]
 [ 6  5]]

Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.61      0.63        18
           1       0.42      0.45      0.43        11

    accuracy                           0.55        29
   macro avg       0.53      0.53      0.53        29
weighted avg       0.56      0.55      0.56        29



In [124]:
df = pd.read_csv("/content/USA_Housing.csv")
df.head()
df.info()
df.shape


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


(5000, 7)

In [125]:
df.describe()


Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562388             5.322283                   6.299250   
50%        68804.286404             5.970429                   7.002902   
75%        75783.338666             6.650808                   7.665871   
max       107701.748378             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928702  9.975771e+05  
50%                        4.050000     36199.406689  1.232669e+06  
75%                        4.490000     42861.290769  1.471210e+06  
max                        6.500000     69621.713378  2.469066e+06

In [126]:
df.isnull().sum()


Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [127]:
df = df.drop("Address", axis=1)


In [128]:
median_price = df["Price"].median()
df["Price"] = df["Price"].apply(lambda x: 1 if x >= median_price else 0)


In [129]:
X = df.drop("Price", axis=1)
y = df["Price"]


In [130]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [131]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [132]:
selector = SelectKBest(score_func=f_classif, k=4)

X_train_selected = selector.fit_transform(X_train_scaled, y_train)
X_test_selected = selector.transform(X_test_scaled)


In [133]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train_selected, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

In [134]:
y_pred = model.predict(X_test_selected)


In [135]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.912

Confusion Matrix:
 [[447  53]
 [ 35 465]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.89      0.91       500
           1       0.90      0.93      0.91       500

    accuracy                           0.91      1000
   macro avg       0.91      0.91      0.91      1000
weighted avg       0.91      0.91      0.91      1000

